# https://github.com/marketplace/actions/latex-compilation
# https://www.reddit.com/r/LaTeX/comments/cudaqz/github_actions_to_compile_latex_documents/

name: Build Letter of Intent
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Build
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Get Repo
        uses: actions/checkout@v2
        with:
          path: main
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: letter.tex
          working_directory: ./
#      - name: Archive Letter
#        uses: actions/upload-artifact@v2
#        with:
#          name: letter-build
#          path: letter.pdf