name: Build Letter of Intent
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Build
    # This job runs on Linux
    runs-on: ubuntu-latest
    container:
      image: schickling/latex:latest
    steps:
      # This step prints an output (time) from the previous step's action.
      - name: Build
        uses: schickling/latex:latest
        run: |
          pwd
          cat letter.tex
          pdflatex letter.tex
      - name: Archive Letter
        uses: actions/upload-artifact@v2
        with:
          name: letter-build
          path: letter.pdf