name: Build Letter of Intent
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Build
    # This job runs on Linux
    runs-on: ubuntu-latest
    container:
      image: schickling/latex:latest
    steps:
      - name: Get Repo
        uses: actions/checkout@v2
      - name: Build
        run: |
          pwd
          cat letter.tex
          pdflatex letter.tex
      - name: Archive Letter
        uses: actions/upload-artifact@v2
        with:
          name: letter-build
          path: letter.pdf